### ISSUE TITLE
Can't find ROM after install from code (raspbian)

### ISSUE THREAD

**Issue by cpcbegin** [ColinPitrat/caprice32#164] opened 2020-05-11 15:13 UTC
I install the latest versión of caprice32 v4.6.0 with these commands:
```
sudo apt install git build-essential libsdl1.2-dev libfreetype6-dev libpng-dev zlib1g-dev
git clone https://github.com/ColinPitrat/caprice32 caprice32cp
cd caprice32cp
git pull
make
sudo make install
```
Previous versions runs OK but the new one only works in path where I compile it, in any other path show this error:

> ERROR   src/cap32.cpp:951 - Couldn't open ROM file '/home/pi/opt/rom//cpc6128.rom'
> ERROR   src/cap32.cpp:1092 - Failed patching the ROM

**Comment by ColinPitrat** [comment] 2020-05-13 14:14
Do you have a message in output saying which configuration file is used?

**Comment by ColinPitrat** [comment] 2020-05-13 14:26
Indeed, the `install` make target is broken.
The problem is that it puts the config in `/etc/cap32.cfg` with the default values for all the paths (./) and the resources under `/usr/local/share/caprice32`.
We'd need to patch the cap32.cfg when we install it.

**Comment by ColinPitrat** [comment] 2020-05-13 14:35
To properly support this we need to:
 - Pass DESTDIR to the build commands
 - Use DESTDIR in sources to look for the config ($DESTDIR/etc/cap32.cfg instead of /etc/cap32.cfg)
 - Either patch the config to put the proper values for the paths or pass a $RESOURCESDIR to the build ($DESTDIR/$prefix) to use it as default values.

I think I prefer the patching for the config. The simplest is to have a config template that is used both to generate installed config (by replacing a pattern by the resources dir) and the local cap32.cfg (by removing the paths that have the pattern)

**Comment by ColinPitrat** [comment] 2020-05-14 11:56
This should be fixed with the following changes:
 - 84e0ea044c1304b2ea085549acf229b27f98132e
 - bc05a7a8dd51e6cd78f7b6fc3855cdc5f2093b9b
 - e842d4acb53a8a318e1e6edfa1e11a8b52806fa8

**Comment by cpcbegin** [comment] 2020-05-20 20:54
Perfect, now I can run again cap32 in any directory.
Thanks a lot, now you can close this issue.

**Comment by 2play** [comment] 2020-06-15 13:53
As a workaround I have resolved this in the past by adding the actual path of where my binary will be, instead the
`APP_PATH="**$PWD**"`

With above if the compile folder exists then even if moved still works (but we dont want the extra files) :-)

**Closed** 2020-06-15 16:22 UTC
