### ISSUE TITLE
Possible Menu Enhancements

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#25] opened 2016-07-25 10:05 UTC
Would it be too much of a hassle if the F1 menu contained an option to enable or disable the joystick via a checkbox?

By default, cap32.cfg, has the joystick enabled and you have to manually edit the cfg file to disable it. This result in multiple arrow characters when the emulator loads since the mouse movements are considered as joystick key presses.

It would also be nice to include a choice of the plus series from the menu (not sure whether this has been implemented yet since I cannot test right now but just got the idea in mind)

Thanks

**Comment by ColinPitrat** [comment] 2016-07-25 11:39
The first one is a duplicate of issue #20 (there's also issue #8 for a checkbox for joystick emulation). I definitely plan to do it in the coming weeks (maybe week if everything goes well).

The second will be implemented as part of issue #15 (plus support) when it will be ready (the least required being my only non-self tester (you) to be ablt to have it start without crashing :-)). I think this should be the case now but I'd like you to double-check.

**Closed** 2016-07-25 11:39 UTC
Labels: duplicate
