### ISSUE TITLE
Either the condition '!pbRAMbuffer' is redundant or there is pointer arithmetic with NULL pointer

### ISSUE THREAD

**Issue by ZanyXDev** [ColinPitrat/caprice32#184] opened 2021-03-17 18:13 UTC
A long long time ago when dinosaurs roamed the earth and Turbo C++ was ruling the world of C++ programmers, 
new actually returned NULL, but now new throw an exception on failure.
https://github.com/ColinPitrat/caprice32/blob/584d4ab6f4ce178b0a83a6a2d95119213c86fda6/src/cap32.cpp#L1082
Either usages pointer arithmetic with NULL pointer
https://github.com/ColinPitrat/caprice32/blob/584d4ab6f4ce178b0a83a6a2d95119213c86fda6/src/cap32.cpp#L1084
Either condition is redundant
https://github.com/ColinPitrat/caprice32/blob/584d4ab6f4ce178b0a83a6a2d95119213c86fda6/src/cap32.cpp#L1087

**Comment by ColinPitrat** [comment] 2021-03-18 12:18
> A long long time ago when dinosaurs roamed the earth and Turbo C++ was ruling the world of C++ programmers,

Well, that's a bit of an exaggeration. caprice32 was born at a time where such a behavior was common (The 32 in the name highlights how 32 bits platform were cool at the time). Although historically, these were probably mallocs that I replaced by new at some point.

In case the pointer could be null, the arithmetic is harmless (although undefined behavior) as the result is never used.
Arguably, dereferencing the null pointers should also be harmless but it could potentially be hard to identify the root cause of the issue.

In practice, I agree the condition is redundant and quite useless. This wouldn't be my priority to fix though as this would just remove 3 lines of code.
But I'd welcome a PR that would get rid of all ERR_OUT_OF_MEMORY references by removing the last places where it follows a call to malloc.

**Comment by ZanyXDev** [comment] 2021-03-19 13:38
Using exceptions like 

```
try
    {
        char* emergency_memory = new char[32768];
    }
    catch (const std::bad_alloc& e)
    {
        delete[] emergency_memory;        
        std::cout << "Data Allocation failed:" << e.what() << std::endl;
        return false;
    }
```

is appropriate for the project's coding style?

**Comment by ZanyXDev** [comment] 2021-03-19 14:00
But mix with exception-based code and error-code-based code may be bad supported :(

**Comment by ColinPitrat** [comment] 2021-04-01 16:20
Gave a try with my own LD_PRELOAD to make the malloc fail exactly when I want too.

With the following code:

```
   pbGPBuffer = new byte [128*1024]; // attempt to allocate the general purpose buffer
   std::cout << "cpitrat here" << std::endl;
   pbRAMbuffer = new byte [CPC.ram_size*1024 + 1]; // allocate memory for desired amount of RAM
   std::cout << "cpitrat there" << std::endl;
   // Ensure 1 byte is available before pbRAM as prerender_normal*_plus can read it
   pbRAM = pbRAMbuffer + 1; 
```

and the library configured to fail the malloc for pbRAMbuffer, the result is the following:

```
cpitrat here
Malloc 1 for 131073 bytes
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

This is, in my opinion, a perfectly acceptable behavior. No need to catch the exception nor to check for nullptr in my opinion.
The program terminating with this message is, I think clear enough. It's unlikely we'll manage to do anything good if malloc fails anyway.

**Comment by ColinPitrat** [comment] 2021-04-01 16:30
I'll close this following the removal of the checks for nullptr after new.
There are remaining usages of ERR_OUT_OF_MEMORY but they are after some malloc. I added a TODO to remove them and get rid of the error code.

**Closed by ColinPitrat** 2021-04-01 16:30 UTC

**Comment by ZanyXDev** [comment] 2021-04-28 15:46
I hope this helps
https://github.com/jemalloc/jemalloc
