### ISSUE TITLE
Manual page doesn't work

### ISSUE THREAD

**Issue by mpoppins** [ColinPitrat/caprice32#118] opened 2018-12-01 22:53 UTC
When i click on the link to the manual I get Table not accessible error.

**Comment by ColinPitrat** [comment] 2018-12-02 08:14
Thanks for reporting this. It seems https://htmlpreview.github.io/ is broken

**Comment by ColinPitrat** [comment] 2018-12-02 08:17
The issue is tracked by htmlpreview repository:
https://github.com/htmlpreview/htmlpreview.github.com/issues/62

**Comment by mpoppins** [comment] 2018-12-02 08:59
ok - no great rush. i'm a full stack whose first computer was the 6128.

**Comment by ColinPitrat** [comment] 2018-12-02 09:09
You can still read the man page here though: 
https://github.com/ColinPitrat/caprice32/blob/master/doc/man6/cap32.6

Or just download https://github.com/ColinPitrat/caprice32/blob/master/doc/man.html and open it in your browser

**Comment by mpoppins** [comment] 2018-12-02 09:30
ok thanks

**Comment by mpoppins** [comment] 2018-12-02 09:45
you have any original hardware?

**Comment by ColinPitrat** [comment] 2018-12-03 18:43
Not anymore, but it's christmas soon if someone wants to send me a gift ;-)
BTW, link is now fixed: http://htmlpreview.github.io/?https://github.com/ColinPitrat/caprice32/blob/master/doc/man.html

**Closed by ColinPitrat** 2018-12-03 18:43 UTC
