### ISSUE TITLE
ALSA message in terminal

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#19] opened 2016-07-19 04:40 UTC
I played a bit Fruity Frank and when I quit the emulator, in the terminal there were a lot of messages like the below:

> ALSA lib pcm.c:7963:(snd_pcm_recover ) underrun occurred

Is that something that can be fixed from caprice32 or shall we just ignore it since it is something ALSA related?

**Comment by ColinPitrat** [comment] 2016-07-19 10:38
I have a few of them too, I never paid too much attention to it.

ALSA is the sound library. A buffer underrun means that ALSA had nothing to play at some point in time, i.e that caprice isn't providing enough data for ALSA to play sounds constantly.

I never noticed significant issue (but I often play in a noisy environment with a low volume).
Do you observe some degradation in the sound ?

It's worth having a look anyway as this may hide an issue.

**Comment by bert003** [comment] 2016-07-19 11:40
No issue in the sound at all, just a lot of those messages in the console.

I guess this message happens when the buffer is empty, right?

Tried some google search but everyone is talking about a conflict with pulseaudio. However I do not have pulse audio installed...

**Comment by bert003** [comment] 2016-07-19 17:40
No luck for a solution on my end... can you replicate the alsa message on your end please?

Maybe it is something related to VirtualBox?

**Comment by ColinPitrat** [comment] 2016-07-20 09:31
I'm pretty sure I already saw this message but now that I want to have a look at it, I don't have it anymore ! Anyway as long as the sound is OK, no need to worry about it.

**Comment by bert003** [comment] 2016-07-20 11:49
Ok I'll ignore it then. Thanks

**Comment by ColinPitrat** [comment] 2017-03-19 21:40
I observed the issue in two cases:
 - when caprice is running below 100% of the speed
 - when using alsa over pulseaudio
In both cases, this has no impact on sound quality. Moreover, the same issue can be observed in other ALSA clients in the same cases.

I'll close this as 'work as intended'.

**Closed by ColinPitrat** 2017-03-19 21:40 UTC
Labels: bug
