### ISSUE TITLE
Linux snap app command line path with space issue

### ISSUE THREAD

**Issue by anonyme-x22** [ColinPitrat/caprice32#232] opened 2023-01-06 01:34 UTC
Hi,

I would like to open a .dsk which contains space in its name.
Tried with quote don't works?

Thanks in advance,
Have a good day,
Rgds,

**Comment by ColinPitrat** [comment] 2023-01-06 08:21
Can you please provide more details? What command are you running? You mention snap app, where does it come from?

**Comment by anonyme-x22** [comment] 2023-01-09 21:04
Hi,
yes of course:

Version 4.5
Latest/stable channel
From discover app downloader
author: stan michalski

Command line:
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher 

Tested:
 Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher /xxx/inertie.dsk OK
 Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher "/xxx/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk"  KO

Thanks in advance,
Have a good day,
Rgds,

**Comment by ColinPitrat** [comment] 2023-01-10 12:25
Thanks. That's not part of caprice32 project, it's a user contributed snap:
https://snapcraft.io/caprice32

You could try the "Contact Stan MICHALSKI" link.

Before that, you may want to dig a bit more to have more details to provide.

When you say KO, what's happening? Is there an error message in the console?

**Comment by anonyme-x22** [comment] 2023-01-11 08:10
Hi,

On linux it's terrible about the snap support they are always outside the main one.
I will try, but i doubt to get a better answer than in the main support i think he just compiled the latest stable , made a snap package on discover and that's all...
Anyway here is the requested information:
terminal launch:
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher "/media/phase_lot/Jeux Consol/Amstrad Cpc/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk"
Result:
ERROR   src/slotshandler.cpp:624 - File not found: 2).dsk

Thanks in advance,
Have a good day,
Rgds,

**Comment by christopheNan** [comment] 2023-01-11 10:23
Hello,
What about replacing double quotes (") by single quotes (')?

**Comment by ColinPitrat** [comment] 2023-01-11 10:50
I think the issue is that the argument are forwarded somehow, without being quoted (e.g. caprice32.launcher is a shell script which then calls cap32).

If this is the case, you would have to double the quotes, or mix quotes and single quotes.

For example:

```
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher "\"/media/phase_lot/Jeux Consol/Amstrad Cpc/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk\""
```

Or with single quotes to avoid the escaping:

```
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher '"/media/phase_lot/Jeux Consol/Amstrad Cpc/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk"'
```

If it still doesn't work, you may need another level of quotes:

```
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher '"\"/media/phase_lot/Jeux Consol/Amstrad Cpc/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk\""'
```

Definitely not great, so maybe the snap owner could change something to quote arguments they receive.

**Comment by ColinPitrat** [comment] 2023-01-12 10:05
Ah, there are quotes around the `$@` so single quotes around double quotes won't work, but the reverse may:

```
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher "'\"/media/phase_lot/Jeux Consol/Amstrad Cpc/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk\"'"
```

In any case this isn't very usable (at this point you're better off renaming the file). So the snap should be fixed.

**Closed by ColinPitrat** 2023-01-12 10:05 UTC

**Comment by anonyme-x22** [comment] 2023-01-13 18:51
Hi,

that don't works also:
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/caprice32_launcher.desktop /snap/bin/caprice32.launcher "'\"/media/phase_lot/Jeux Consol/Amstrad Cpc/Inertie (1987)(Ubi Soft)(fr)(Disk 1 of 2).dsk\"'"
Result
String ignored

Yes i tought about copying it somewhere without space and rename it before opening but that's also not very usable.
Hope stan would do something!

Thanks in advance,
Rgds,

**Comment by stanmichalski** [comment] 2023-01-29 22:30
Hello,
Happy you tried my Caprice32 snap.
I did a new release of this snap to try to fix that issue.
Path on the snap store is always the same : https://snapcraft.io/caprice32

News:
- caprice32launcher changed to:
---
# Launching binary
echo -e "Launching binary cap32"
fic1=$1
fic2=$2
echo -e "File A = ${fic1}"
echo -e "File B = ${fic2}"
exec ${FIC_SNAP_BINARY} --cfg_file=${FIC_USER_CONFIG} "${fic1}" "${fic2}"
---
- jump from Caprice32 v4.5.0 to Caprice32 v4.6.0
- jump from snap core (16)  to core20
- little changes about my caprice32launcher
- update Caprice32 snap description on snap store :
---
CPC programs and games directory storage (disk,tape,cart,snap) : $HOME/snap/caprice32 Caprice32 source code is available at https://github.com/ColinPitrat/caprice32

Exemples how to launch Caprice32 : snap run caprice32.launcher snap run caprice32.launcher "pathGameA.dsk" snap run caprice32.launcher "pathGameA.dsk" "pathGameA.dsk" Notice : use double quote if pathfile contains spaces.

To use joystick into strict confinement mode run command : snap connect caprice32:joystick

To calibrate joystick/pad run command : sudo jstest-gtk

To display your snaps in desktop launcher run command : sudo ln -s /var/lib/snapd/desktop/applications /usr/share/applications/snapd
---

Regards. Stan
